---
- name: fetch data_log_folder to host
  hosts: testbench
  remote_user: root
  tasks:
    - name: start to fetch logs
      fetch: src=/tmp/run_pulls/data_log_folder.zip dest=/home/buildbot/ansible_tasks/task_debug/ flat=yes
