---
- name: start to run task
  hosts: localhost
  remote_user: root
  tasks:
    - name: start to generate target docker image
      shell: python /home/testhouse/ansible_tasks/works.py /home/testhouse/ansible_tasks/debug/omds/config/debug/debug
- name: Run IPATH service
  hosts: test_bench
  remote_user: root
  tasks:
    - name: install expect if no install
      apt: name=expect state=present
    - name: delete old omds_client package
      file: dest=/tmp/omds_client state=absent
    - name: copy omds_client package to node server
      copy: src=/home/testhouse/ansible_tasks/task_debug/omds_client dest=/tmp/
    - name: delete old run_pulls package
      file: dest=/tmp/run_pulls state=absent
    - name: copy run_pulls package to node server
      copy: src=/home/testhouse/ansible_tasks/task_debug/omds_server/run_pulls dest=/tmp/
    - name: generate report link
      command: python /tmp/omds_client/return_ip_address.py
      register: result
    - name: please copy below report link to check IPATH running process and TCR link
      debug: var=result.stdout_lines
    - name: start to run, it will last long time ...
      command: python /tmp/omds_client/start.py 
    - name: start to run collect data script ...
      command: python /tmp/run_pulls/run.py
    - name: start to run uploader script ...
      command: expect /tmp/run_pulls/my_uploader.sh

