---
- name: start to run task
  hosts: localhost
  remote_user: root
  tasks:
    - name: start to generate target docker image
      shell: python /home/buildbot/ansible_tasks/work.py /home/buildbot/ansible_tasks/debug/omds/config/debug/debug
- name: Run IPATH service
  hosts: testbench
  remote_user: root
  tasks:
    - name: delete old omds_client package
      file: dest=/tmp/omds_client state=absent
    - name: copy omds_client package to node server
      copy: src=/home/buildbot/ansible_tasks/task_debug/omds_client dest=/tmp/
    - name: delete old run_pulls package
      file: dest=/tmp/run_pulls state=absent
    - name: copy run_pulls package to node server
      copy: src=/home/buildbot/ansible_tasks/task_debug/omds_server/run_pulls dest=/tmp/
    - name: generate report link
      command: python /tmp/omds_client/return_ip_address.py
      register: result
    - name: please copy below report link to check IPATH running process and TCR link
      debug: var=result.stdout_lines
    - name: start to run, it will last long time ...
      command: python /tmp/omds_client/start.py 
    - name: start to run collect data script ...
      command: python /tmp/run_pulls/run.py
- name: fetch data_log_folder to host
  hosts: localhost
  remote_user: root
  tasks:
    - name: start to fetch logs
      fetch: src=/tmp/run_pulls/data_log_folder.zip dest=/home/buildbot/ansible_tasks/task_debug/ flat=yes Fail_on_missing=Yes

